// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.3
// source: roles.proto

package vehicle_logs_service_mock

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// VehicleRegistrationRole models the available roles a user can have in relation to a 21MM vehicle
// There can be only 1 PRIMARY, but multiple SECONDARIES
// See the VehicleRegistrationService for more information on how the role affects what a user can do with a vehicle
type VehicleRegistrationRole int32

const (
	VehicleRegistrationRole_PRIMARY   VehicleRegistrationRole = 0
	VehicleRegistrationRole_SECONDARY VehicleRegistrationRole = 1
)

// Enum value maps for VehicleRegistrationRole.
var (
	VehicleRegistrationRole_name = map[int32]string{
		0: "PRIMARY",
		1: "SECONDARY",
	}
	VehicleRegistrationRole_value = map[string]int32{
		"PRIMARY":   0,
		"SECONDARY": 1,
	}
)

func (x VehicleRegistrationRole) Enum() *VehicleRegistrationRole {
	p := new(VehicleRegistrationRole)
	*p = x
	return p
}

func (x VehicleRegistrationRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VehicleRegistrationRole) Descriptor() protoreflect.EnumDescriptor {
	return file_roles_proto_enumTypes[0].Descriptor()
}

func (VehicleRegistrationRole) Type() protoreflect.EnumType {
	return &file_roles_proto_enumTypes[0]
}

func (x VehicleRegistrationRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VehicleRegistrationRole.Descriptor instead.
func (VehicleRegistrationRole) EnumDescriptor() ([]byte, []int) {
	return file_roles_proto_rawDescGZIP(), []int{0}
}

var File_roles_proto protoreflect.FileDescriptor

var file_roles_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x63,
	0x6f, 0x6d, 0x2e, 0x74, 0x6f, 0x79, 0x6f, 0x74, 0x61, 0x2e, 0x63, 0x74, 0x70, 0x2e, 0x76, 0x31,
	0x2a, 0x35, 0x0a, 0x17, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x50,
	0x52, 0x49, 0x4d, 0x41, 0x52, 0x59, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x45, 0x43, 0x4f,
	0x4e, 0x44, 0x41, 0x52, 0x59, 0x10, 0x01, 0x42, 0x1d, 0x5a, 0x1b, 0x2e, 0x3b, 0x76, 0x65, 0x68,
	0x69, 0x63, 0x6c, 0x65, 0x2d, 0x6c, 0x6f, 0x67, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2d, 0x6d, 0x6f, 0x63, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_roles_proto_rawDescOnce sync.Once
	file_roles_proto_rawDescData = file_roles_proto_rawDesc
)

func file_roles_proto_rawDescGZIP() []byte {
	file_roles_proto_rawDescOnce.Do(func() {
		file_roles_proto_rawDescData = protoimpl.X.CompressGZIP(file_roles_proto_rawDescData)
	})
	return file_roles_proto_rawDescData
}

var file_roles_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_roles_proto_goTypes = []interface{}{
	(VehicleRegistrationRole)(0), // 0: com.toyota.ctp.v1.VehicleRegistrationRole
}
var file_roles_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_roles_proto_init() }
func file_roles_proto_init() {
	if File_roles_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_roles_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_roles_proto_goTypes,
		DependencyIndexes: file_roles_proto_depIdxs,
		EnumInfos:         file_roles_proto_enumTypes,
	}.Build()
	File_roles_proto = out.File
	file_roles_proto_rawDesc = nil
	file_roles_proto_goTypes = nil
	file_roles_proto_depIdxs = nil
}
